<div class="alert alert-block alert-danger">
    <b><p style="font-size: XX-large"> <font color="mediumvioletred">Indexing and Selection</font></p></b></div>

In [2]:
import numpy as np

In NumPy there are different ways to access or change values in arrays

* Indexing
* Slicing
* Fancy indexing
* Boolean indexing / masking
* And combinations thereof

----

<div class="alert alert-block alert-warning">
    <b><p style="font-size: XX-large"> <font color="mediumvioletred">Indexing</font></p></b></div>

* An array is indexed by a tuple of integers, e.g., **`a [row, col]`** = $ a[i,j]$ 
* In Python list we use **` a[i][j]`** = a[row][col]

In [3]:
a = np.arange(0,20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
# row index 2, column indedx 3
a[2,3]

13

In [5]:
# row index 3
a[3]

array([15, 16, 17, 18, 19])

---

<div class="alert alert-block alert-warning">
    <b><p style="font-size: XX-large"> <font color="chocolate">Slicing</font></p></b></div>

* Slicing allows you to select multiple sequential rows/columns.
* To select all the elements along one of the dimensions use colon `:`

In [6]:
a = np.arange(0,20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
# rows index 1 and 2

a[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
# columns 0,1
a[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [10]:
# 4th row, 3rd column onward
a[3, 2:]

array([17, 18, 19])

----

<div class="alert alert-block alert-danger">
    <b><p style="font-size: XX-large"> <font color="orangered">Fancy Slicing</font></p></b></div>

You can select multiple non sequential rows/columns by **specifying a list of indexes** in `[ , , ]`.

In [11]:
a = np.arange(0, 20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
# 1st and 3rd row
a[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [13]:
a[:, [1,3]]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

----

<div class="alert alert-block alert-info">
    <b><p style="font-size: XX-large"> <font color="royalblue">Boolean Indexing (Masking)</font></p></b></div>

* Boolean indexing is used to **select elements** of the array that **satisfy some condition**

* The boolean expression itself creates an array of boolean values that indicates which elements from the array to return.

In [14]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
# Note the boolean expression itself

a % 2 == 0

array([ True, False,  True, False,  True])

In [16]:
# extract even numbers

a[a % 2 == 0]

array([0, 2, 4])

---

<div class="alert alert-block alert-danger">
    <b><p style="font-size: XX-large"> <font color="purple">Changing Elements</font></p></b></div>

We can make changes to a sliced or indexed array and these changes are reflected in the original array.

In [17]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
a[[1,2,3,7]] = 888
a

array([  0, 888, 888, 888,   4,   5,   6, 888,   8,   9,  10,  11,  12,
        13,  14,  15])

In [19]:
# change all the values that are less than 9 to -4

a [a < 9] = -4

a

array([ -4, 888, 888, 888,  -4,  -4,  -4, 888,  -4,   9,  10,  11,  12,
        13,  14,  15])

---

# Exercise

Use slicing to select the highlighted elements from the given matrix:

<img src = "Pics/slice.jpg" width = "600">

# Solutions

In [ ]:
import numpy as np

In [20]:
A = np.arange(1, 13).reshape(4,3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
# (a)

A[2]

array([7, 8, 9])

In [22]:
# (b)

A[:, 1]

array([ 2,  5,  8, 11])

In [23]:
# (c)

A[1:3, 1:]

array([[5, 6],
       [8, 9]])

In [24]:
# (d)

A[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [25]:
# (d)

A[0::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
# (e)

A[2:, :2]

array([[ 7,  8],
       [10, 11]])

In [30]:
# (f)

A[[1,3], ::2]

array([[ 4,  6],
       [10, 12]])

----

# Done!