<div class="alert alert-block alert-info">
    <b><p style="font-size: XX-large"> <font color="royalblue">Sorting Functions</font></p></b></div>

<img src = "Pics/sortt.jpg" width="600">

* Although Python has built in sort() and sorted() functions for lists, NumPy's np.sort function turns out to be much more efficient.
* By default np.sort () uses quicksort, though mergesort and heapsort are also available

In [3]:
import numpy as np

In [4]:
a = np.array([3, 1, 4, 2, 5])

In [5]:
np.sort(a)

array([1, 2, 3, 4, 5])

In [6]:
a

array([3, 1, 4, 2, 5])

In [7]:
a.sort() # in place

In [8]:
a

array([1, 2, 3, 4, 5])

---

In [9]:
a = np.random.randint(10, size=(4,6))
a

array([[1, 7, 4, 0, 3, 6],
       [9, 0, 8, 0, 6, 4],
       [9, 2, 2, 9, 6, 7],
       [3, 8, 2, 1, 4, 4]])

In [10]:
np.sort(a, axis = 0) # sort each column

array([[1, 0, 2, 0, 3, 4],
       [3, 2, 2, 0, 4, 4],
       [9, 7, 4, 1, 6, 6],
       [9, 8, 8, 9, 6, 7]])

In [11]:
np.sort(a, axis = 1) # sort each row?

array([[0, 1, 3, 4, 6, 7],
       [0, 0, 4, 6, 8, 9],
       [2, 2, 6, 7, 9, 9],
       [1, 2, 3, 4, 4, 8]])

---

In [ ]:
a = [ 7, 3, 10, 2, 8]
np.argsort(a)

----

<div class="alert alert-block alert-warning">
    <b><p style="font-size: XX-large"> <font color="Chocolate">Searching Functions</font></p></b></div>

<img src = "Pics/search.jpg" width = "600">

In [15]:
a = np.array([[7, 2, 5, 1, 4, 6, 3],[4, 8, 9, 5, 4, 4, 4]])
print(a)
np.where(a>4)

[[7 2 5 1 4 6 3]
 [4 8 9 5 4 4 4]]


(array([0, 0, 0, 1, 1, 1]), array([0, 2, 5, 1, 2, 3]))

In [13]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.where(a>4)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

---

In [23]:
b = np.array([1, 2, 6, 4, 2, 3, 2, 6, 5 , 5])

np.unique(b)  # write the elements of the array without repeating ones and sort them

array([1, 2, 3, 4, 5, 6])

In [27]:
print(a)
values, counts = np.unique(a, return_counts = True)

counts

[1 2 6 4 2 3 2 6]


array([1, 3, 1, 1, 2])

---

<div class="alert alert-block alert-danger">
    <b><p style="font-size: XX-large"> <font color="mediumvioletred">Joining Functions</font></p></b></div>

<img src = "Pics/joining.jpg" width = "600">

In [28]:
a = np.array([0, 1, 2])

np.append(a, [20, 30])

array([ 0,  1,  2, 20, 30])

In [29]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.append(b, [[0,0,0]], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

In [31]:
np.append(b, [[0],[0],[0]], axis = 1)

array([[0, 1, 2, 0],
       [3, 4, 5, 0],
       [6, 7, 8, 0]])

---

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

In [33]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

----

# Done!