<div class="alert alert-block alert-info">
    <b><p style="font-size: XX-large"><font color = "royalblue">Eigenvalues & Eigenvectors</font></p></b>

<img src = "Pics/eigmon.png">
<a href = "http://wiki.pathmind.com/eigenvector">image source</a>

# <font color = "royalblue">Applications:</font>

Eigenvalues and eigenvectors are crucial tools in **linear algebra**, especially in data science and machine learning. Let's break it down:

1. **Linear transformations and matrices**: When you apply a linear transformation (such as rotation or scaling) to data, eigenvalues and eigenvectors help describe how the transformation affects the data. Eigenvectors indicate the directions in which the transformation stretches or shrinks the data, while eigenvalues describe how much it stretches or shrinks in those directions.

---
2. Applications in machine learning: These concepts are widely used in tasks like:

    * **Feature extraction**: Identifying the most informative parts of the data.
    * **Dimensionality reduction**: Simplifying data by reducing the number of variables while retaining its essential structure.
    * **Clustering**: Grouping similar data points based on patterns captured through eigenvectors.
    
    
    ---
3. **Principal Component Analysis (PCA)**: Eigenvalues and eigenvectors are central to PCA, which reduces the dimensionality of data by transforming it into a set of uncorrelated variables (called principal components). These components capture the most variance in the data, with the highest eigenvalues representing the most significant directions. This reduction results in simpler models that are easier to compute and tend to generalize better to new data.

In short, eigenvalues and eigenvectors allow us to analyze and manipulate data efficiently by focusing on the most significant features and patterns.  

<a href = "https://vitalflux.com/why-when-use-eigenvalue-eigenvector/#:~:text=Eigenvalues%20and%20eigenvectors%20can%20be,represented%20by%20the%20corresponding%20eigenvalue."> Nice article explaining why we use eigenvectors</a>

---

# <font color = "royalblue">Definition</font>

* **Eigenvectors** are the vectors that when multiplied by a matrix result in another vector having the same direction but scaled in (forward or reverse) direction by a magnitude of the scaler multiple which can be termed as **Eigenvalue**.

<img src = "Pics/eigen.png">
<a href = "https://www.mathsisfun.com/algebra/eigenvalue.html">Image Source</a>

* Intuitively, this definition means that multiplying $A$ by the vector $X \neq 0$ results in a new vector that points in the same direction as $X$ , but scaled by a factor $\lambda$

<img src = "Pics/eigen2.png">

# <font color = "royalblue">Calculation</font>

<img src = "Pics/eigen6.png"  width = "400">

# <font color = "royalblue">Example</font>

<img src = "Pics/eigen5.png" width = "500">

# <font color = "royalblue">In Python</font>


* **`np.linalg.eig(A)`** computes the eigenvalues and eigenvectors of a Matrix $A$

In [5]:
import numpy as np

In [6]:
A = np.array([[1,4],[3,2]])
print(A)

[[1 4]
 [3 2]]


In [7]:
eigen_vals, eigen_vect = np.linalg.eig(A)

In [8]:
eigen_vals

array([-2.,  5.])

In [9]:
eigen_vect

array([[-0.8       , -0.70710678],
       [ 0.6       , -0.70710678]])

---

# Exercise:

1.  Create the following matrix:
    <img src = "Pics/met.jpg">

2.  Find the transpose matrix of $A$
3. Compute the rank of $A$ (rank is the number of linearly independent rows - search on the linear algebra library)
4. Compute the determinant of $A$
5. Compute the inverse of $A$
6. Compute the eigenvalues and eigenvectors of $A$


# Solutions

In [ ]:
# 1

import numpy as np
A = np.array([[1, 2, 3], 
              [0, 1, 4], 
              [ 5, 6, 0]])
print (A)

In [ ]:
# 2

A.T

In [ ]:
# 3
# Source: <a href = "https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html"> Source</a>

np.linalg.matrix_rank(A)

In [ ]:
# 4

np.linalg.inv(A)

In [ ]:
# 5

eigen_vals, eigen_vecs = np.linalg.eig(A)

In [ ]:
eigen_vals

In [ ]:
eigen_vecs

---

# Done!