<div class="alert alert-block alert-info">
    <b><p style="font-size: xx-large"><font color = "darkblue">NumPy Arrays</font></p></b></div>

* Numpy arrays essentially come in two flavors: 
    1. vectors
    2. matrices.
    
    
* Vectors are strictly 1-d arrays and matrices are 2-d (Note that a matrix can still have only one row or one column).

<img src ="Pics/arrays.png" width = "500">
<a href="https://predictivehacks.com/tips-about-numpy-arrays/">Image Source</a>

---

<div class="alert alert-block alert-warning">
    <b><p style="font-size: xx-large"><font color = "red">Creating NumPy Arrays</font></p></b></div>

* The array object in NumPy is called ndarray.
    * 0-D arrays are scalars, i.e. numbers.
    * 1-D (one dimensional or uni-dimensional) arrays are like lists
    * 2-D arrays are matrices
    * 3-D arrays have a matrix in every dimension
    
* All the elements in an array must be of the same data type
    
    
* To create a NumPy ndarray object passing a list to the **`np.array()`** function.

In [ ]:
#import numpy first

import numpy as np

# Create 0-dim array

In [ ]:
a = np.array(79)
print(a)

In [ ]:
a.shape

---

# Create 1-dim array

In [ ]:
a = np.array([1,3,4,5,6,7])
print(a)

In [ ]:
a.shape

---

# Create 2-dim array

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

In [ ]:
A.shape

---

# Create 3-dim array

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[10,6,389],[5,6,7]],[[10,6,389],[5,6,7]],[[10,6,389],[5,6,7]]])
arr

In [ ]:
arr.shape

# Example

Make a numpy array with the shape (2,3,4)

In [ ]:
np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]],[[7,8,9,6],[2,3,4,5],[5,6,7,8]])

---

<div class="alert alert-block alert-warning">
    <b><p style="font-size: xx-large"><font color = "orange">Array Attributes</font></p></b></div>

Press **`tab`** after the array's name and dot `.` to see all the arrays attributes.

* Some useful array attributes:

    1. **`dtype`**: gives the type of the elements in the array

    2. **`ndim`**: gives the array’s dimensions

    3. **`shape`**: gives a tuple specifying the size of the array along each dimension

# <font color = "orange"> Data Types in Numpy: 
<img src = "Pics/dtypes.Jpg">
<a href = "https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html">Image Source</a>

# <font color = "orange">Python Integers: More Than Just Numbers"

- A Python integer is more than just a simple integer; it is part of a complex C structure.
- When you define an integer in Python, it is not stored as a raw value like in C. Instead, it’s a **pointer to a structure** that contains the following components:

    * ob_refcnt: A **reference count for memory management**.
    * ob_type: The **type** of the variable.
    * ob_size: The **size** of the object.
    * ob_digit: The **actual** integer value.

- This extra information, while making Python flexible and dynamic, introduces overhead compared to a C integer, which is just a direct label to memory storing the value.

---

In [ ]:
A = np.array([[1, 2.1, 3], [4, 5, 6]])

A

In [ ]:
# data type
A.dtype

In [ ]:
# array's dimention
A.ndim

In [ ]:
# array's shape

A.shape
# The example returns (2, 3), 
# which means that the array has 2 dimensions,
# where the first dimension has 2 elements and the second has 3.


----

In [ ]:
arr = np.array([[[1, 2.5, 3], [4, 5.6, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

In [ ]:
arr.dtype

In [ ]:
arr.ndim

In [ ]:
arr.shape

----

<div class="alert alert-block alert-danger">
    <b><p style="font-size: xx-large"><font color = "darkpink"> Arrays with Specific Values</font></p></b></div>

* **`zeros()`**, **`ones()`**, **`full()`**: return a new array of given shape and type, filled with zeros, ones or a specified value
    
    
* **`eye`**: creates identity matrix

In [ ]:
# a 1=D array of all 0

a = np.zeros(8)
a

In [ ]:
# a matrix 5*3 of all 1

np.ones((5,3))

In [ ]:
 # a 3-D array filled with 9

np.full((2,3,5),9)

---

<div class="alert alert-block alert-info">
    <b><p style="font-size: xx-large"><font color = "orangered"> Creating Arrays with arange</font></p></b></div>

1. **`np.arange([start = 0], stop, [step = 1])`** creates an array from a sequence of numbers, the same as Python's range() function except it can make floating points as well.



2. **`np.linspace(start , stop , [num = 50])`** creates an array of evenly spaced numbers, where stop is included, and num = the number of values


# np.arange vs. np.linspace

1. arange: uses the size of stpes (default=1), linspace: uses the numebr of steps (default=50)
2. arange: not including the end of the interval, linspace: includes the end

In [ ]:
np.arange(5)

In [ ]:
np.arange(30, 100, 5)

---

In [ ]:
# 4 evenly spaced numbers between 0 and pi

np.linspace(0, np.pi, 40)

---

<div class="alert alert-block alert-warning">
    <b><p style="font-size: xx-large"><font color = "orange"> Arrays with Random Values</font></p></b></div>

The module **`np.random`** contains functions to generate random arrays.

1. **`np.random.random (shape)`** creates an array with numbers sampled randomly from the uniform distribution over $[0, 1)$

    * A **uniform distribution** is a type of probability distribution in which all outcomes are equally likely. In other words, every value within a specific range has the same probability of occurring.
    * **Example**: rolling a fair six-sided die, where each number from 1 to 6 has an equal probability of being rolled.

<img src = "Pics/unidis.png" width = "300">



In [ ]:
# 2*5 matrix of random numbers over [0,1) from uniform dist

np.random.random((2,5))

---
2. **`np.random.randint (low , [high], size)`** creates an array with integer numbers sampled from the interval [low, high) upto-not including high.


In [ ]:
# 3*4 matrix of random integers from 10 to 100

np.random.randint(10, 100, (3,4))

---

3. **`np.random.normal (loc= 0.0 , scale = 1.0 , size )`** samples numbers from the normal distribution with `mean = loc` and standard `deviation = scale`.


     * **Normal/Gaussian distribution** is a probability distribution that is symmetric about its mean, with the shape of a bell curve. Data tends to cluster around the central value (mean), with values further from the mean becoming less frequent.
     * **Example**:  test scores in a large class, where most students score around the average, with fewer students scoring very high or very low.

<img src = "Pics/mean.png" width = "500">

In [ ]:
# 4*4 matrix of random numbers with mean 100 and sd 20

np.random.normal(100, 20, (4,4))

------

# <font color = "orangered"> random.seed:
    
* Use **`np.random.seed`** to set the seed for the random number generator, ensuring that you get the same sequence of random numbers each time you run the code.


    
* seed value =  an initial value used by a random number generator to start the sequence of random numbers, for example:
    * seed 0 = first time I run the random generator algoritm, and I get 7,8,9
    * seed 56 = the 56th time I run the algo and I get 6,4,2
    * if you want to get the sequenece 6,4,2 you need to use the seed 56

In [ ]:
# roll a dice two times

np.random.randint(1, 7, size = 2)

In [15]:
# fix numbers, compare seed 0 and seed 10
import numpy as np
np.random.seed(3)
np.random.randint(1, 7, size = 2)

array([3, 1])

----

<div class="alert alert-block alert-warning">
    <b><p style="font-size: xx-large"> <font color="chocolate">Array Attributes</font></p></b></div>

1. **`reshape()`**: to change the dimensions of array, the new shape should have the same number of elements as the original shape


2. **`ravel()`**: to flatten a multidimensional array into one dimension


3.  **`.min()`** and **`.max()`** find the min and max value in an array.


4. **`.argmin()`** and **`argmax()`** find the index locations of min and max in the array.

In [17]:
np.arange(1, 13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

---

In [18]:
a = np.random.randint(10, 20, (5,2))
a

array([[19, 13],
       [18, 18],
       [10, 15],
       [13, 19],
       [19, 15]])

In [19]:
a.ravel()

array([19, 13, 18, 18, 10, 15, 13, 19, 19, 15])

---

In [20]:
b = np.random.randint(0,100,10)
b

array([38, 96, 20, 44, 93, 39, 14, 26, 81, 90])

In [21]:
b.max()

96

In [22]:
b.argmax()

1

<div class="alert alert-block alert-success">
    <b><p style="font-size: xx-large"><font color = "green">Help</font></p></b></div>

Use this syntax: **`np.info(np.function)`**


In [23]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

---

----

# Exercise

* Create an array of 20 even integers from 2 through 40

* Then reshape the result into a 4 by 5 array

# Solution

In [ ]:
x = np.linspace(2, 40, 20)
x.reshape(4, 5)

In [ ]:
np.arange(start = 2,stop = 42, step = 2).reshape(4,5)

In [ ]:
even_integers = np.arange(2, 41, 2).reshape(4, 5)

print(even_integers)

----


# Done!