<div class="alert alert-block alert-info">
    <b><p style="font-size: XX-large"><font color = "blue">Linear Algebra</font></p></b>

<img src = "Pics/lin.png" width = "300">

In [1]:
import numpy as np

<div class="alert alert-block alert-warning">
    <b><p style="font-size: XX-large"><font color = "orangered">Matrices</font></p></b>

* Create special matrices:
    * **`np.eye(N)`** creates identity matrix of size N*N
    * **`np.diag(v)`** creates diagonal matrix from 1-D array v
    
    
* Transpose of a matrix:
    * Use attribute **`.T`** after the matrix to flip the rows and columns
    

* Matrix multiplication: 
    * **np.dot (a,b)** returns the dot product of 1-D arrays(vectors) a and b.
    * **A @ B** returns the matrix multiplication of 2-D arrays(matrices) A and B , we can use np.dot(a,b) as well.

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.diag([4, 5, 6, 7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

---

In [5]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
A.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

----

In [7]:
x = np.array([1, 2])
y = np.array([3, 4])

np.dot(x, y) # = 1*3 + 2*4

11

In [8]:
A = np.array([[4,1], [2,2]])
B = np.array([[1,0], [0,1]])

A @ B # Matrix -multiplication

array([[4, 1],
       [2, 2]])

In [9]:
A @ x # matrix-vector multiplication

array([6, 6])

---

<div class="alert alert-block alert-danger">
    <b><p style="font-size: XX-large"><font color = "mediumvioletred">Linear Algebra Functions</font></p></b>

* The module **`np.linalg`** contains additional fuctions to work with matrices.


* <a href = "https://numpy.org/doc/stable/reference/routines.linalg.html">Full list of linear algebra module</a>



---

# <font color = "mediumvioletred">**Inverse of a Matrix**</font>
* **`np.linalg.inv()`** computes the inverse of a matrix
*  If the matrix is not invertible ( non-singular) a LinAlgError. exception is raised.

<img src = "Pics/inver.png">

In [10]:
a = np.array([[1, 2], [3, 4]])

a

array([[1, 2],
       [3, 4]])

In [11]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

---

# <font color = "mediumvioletred">**Determinant of a Matrix**</font>
* **`np.linalg.det()`** computes the determinant of a matrix


<img src = "Pics/det2.png" width = "500">

<img src = "Pics/3*3.jpeg" width = "500">

In [12]:
A = np.array([[1, 2, 3], 
              [0, 1, 4], 
              [ 0, 6, 1]])

np.linalg.det(A)

-23.0

---

<div class="alert alert-block alert-warning">
    <b><p style="font-size: XX-large"><font color = "chocolate">System of Linear Equations</font></p></b>

* Matrix multiplication:
<img src = "Pics/mul.png" width = "400">

* Matrix representation of a system of linear equations:
<img src = "Pics/sys.png" width = "500">

* So we can write any system of linear equations as $A X = b$:
    * where $A$ is the coefficient matrix
    * $X$ is a variable matrix
    * $b$ is the constant matrix. 

* This system $A X = b$ has a uniqe solution if and only if $A$ is non-singular meaning $|A|\neq 0$ (determinant of $A$ is not zero)

* Then the solution is $X = A^{-1} b$.

* Geometrically:
    * A linear system in three variables determines a collection of planes. The intersection point is the solution.
    


<img src = "Pics/hyperplane.png" width = "400">
<img src = "Pics/linge.png">   
    

* **`np.linalg.solve(A,b)`** computes the solution of the linear matrix equation $Ax = b$

# Example

Solve the following linear system of equations:

<img src = "Pics/sys.jpg">

In [ ]:
A = np.array([[3, -2, 0], 
              [-2, 1, -3], 
              [ 4, 6, 1]])

b = np.array([8, -20, 7])

In [ ]:
np.linalg.solve(A, b)

In [ ]:
# lets find x differently by: inverse of A * b

np.linalg.inv(A) @ b

---

# Done!