<div class="alert alert-block alert-info">
    <b><p style="font-size: XX-large"> <font color="royalblue">Universal Array Functions</font></p></b></div>

* A universal function (or ufunc for short) is a function that performs various element-wise operations on ndarrays.

    * **Perform fast, element-wise operations** on arrays without needing loops.
    * **Support broadcasting**, allowing operations on arrays of different sizes.


* Here is the list: [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html).

In [2]:
import numpy as np

In [3]:
a = np.array([1, 4, 9, 16, 25, 36, 49])

In [4]:
# taking Square Roots element-wise

np.sqrt(a)

array([1., 2., 3., 4., 5., 6., 7.])

In [5]:
# calcualting exponential (e^)

np.exp(a)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21])

In [6]:
# the same as a+a

np.add(a,a)

array([ 2,  8, 18, 32, 50, 72, 98])

In [7]:
#same as a.max()

np.max(a)

49

---

<img src = "Pics/ufunc.jpg">

----

# Trig functions


In [8]:
# generate 5 numbers between 0 and 2*pi

theta = np.linspace(0, 2*np.pi, 5)
theta

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [9]:
# sin/cos

np.cos(theta)

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

---

# Exponential and Logarithm

In [10]:
x = [1, 2, 3]

np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [11]:
# Base-e logarithm of x = ln(x)
    
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [12]:
# Base-2 logarithm of x

np.log2(x)

array([0.       , 1.       , 1.5849625])

----

<div class="alert alert-block alert-danger">
    <b><p style="font-size: XX-large"> <font color="mediumvioletred">Aggregation Functions</font></p></b></div>

* Aggregation functions allow you to get various statistics about your data, such as sum(), max(), var()
 
 
* By default these functions ignore the shape and use all elements in the calculations 

In [13]:
grades = np.array([[87, 96, 70], # grades for Mid1, Mid2, Final
                   [92, 87, 89],
                   [85, 65, 75],
                   [100, 53, 98]])

grades

array([[ 87,  96,  70],
       [ 92,  87,  89],
       [ 85,  65,  75],
       [100,  53,  98]])

In [14]:
grades.max()

100

In [15]:
grades.mean()

83.08333333333333

---

#  <font color="mediumvioletred">Agg. Funcs. on Rows/Columns

* Many aggregation methods can be performed on specific array dimensions
* These methods receive an **`axis`** keyword argument that specifies which dimension to use in the calculation

<img src = "Pics/arrays.png" width = "500">

In [16]:
grades = np.array([[100, 0, 0], # grades of 4 students in Mid1, Mid2, Final
                   [100, 87, 89],
                   [100, 65, 75],
                   [100, 53, 98]])

grades

array([[100,   0,   0],
       [100,  87,  89],
       [100,  65,  75],
       [100,  53,  98]])

In [17]:
grades.mean(axis = 0) # average on each exam

array([100.  ,  51.25,  65.5 ])

In [18]:
grades.mean(axis = 1) # average on each students

array([33.33333333, 92.        , 80.        , 83.66666667])

----

<div class="alert alert-block alert-warning">
    <b><p style="font-size: XX-large"> <font color="orangered">Axis</font></p></b></div>

* Remember the coordinate axis, first axis (x-axis) and the second axis (y-axis)
<img src = "Pics/axis.jpg">

* Numpy axis are the directions along the rows and columns
<img src = "Pics/axis2.jpg">

* When we say **`axis = 0`**, the rows collapse and we do the operations **vertically**.
* When we say **`axis = 1`**, the columns collapse we do the operations **horizontally**.

In [19]:
a = np.arange(0,6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

<img src = "Pics/axis3.jpg">

In [20]:
a.sum(axis = 0)

array([3, 5, 7])

<img src = "Pics/axis4.jpg">

In [ ]:
a.sum(axis = 1)

---

<img src = "Pics/axis5.jpg">

<img src = "Pics/axis6.jpg">
<a href= "https://www.sharpsightlabs.com/blog/numpy-axes-explained/">Image Source</a>

----

<div class="alert alert-block alert-success">
    <b><p style="font-size: XX-large"> <font color="green">Some Agg. Functions</font></p></b></div>

<img src = "Pics/agg1.jpg" width = "600">

In [21]:
ab = np.random.randint(0, 10, (3,3))
ab

array([[6, 1, 5],
       [0, 4, 4],
       [0, 7, 3]])

In [22]:
# check this later
ab.argmin()

3

In [23]:
ab.argmin(axis = 0)

array([1, 0, 2])

In [24]:
ab.argmin(axis = 1)

array([1, 0, 0])

---

In [25]:
print(a)

[[0 1 2]
 [3 4 5]]


In [26]:
# count the number of even values

np.count_nonzero(a % 2 == 0)

3

In [27]:
# count the number of even values in each column

np.count_nonzero(a % 2 == 0, axis = 0)

array([1, 1, 1])

---

In [28]:
print(a)

[[0 1 2]
 [3 4 5]]


In [29]:
# is there any value >5?

np.any(a>5)

False

In [32]:
# are all the values >5?

np.all(a<=5)

True

In [33]:
# are the value in each row greater than 1

np.all(a>1, axis = 1)

array([False,  True])

----

# Exercise


1. Create a matrix of 3 * 5 representing grades of 3 students in 5 exams

2. Fill in the matrix with random integers between 0 and 100

3. Print the grades average of each student

4. Print the standard deviation of grades in each exam

5. Print the index of the exam with the lowest average grade

6. Print the index of the student who got the highest grade in any exam

7. Print the index of the student who has the highest average grade

8. Print all the exams in which the grades average was larger than 80

# solution

In [ ]:
import numpy as np

In [34]:
# 2 Fill in the matrix with random integers between 0 and 100

A = np.random.randint(0, 100, (3,5))
A

array([[62,  3, 62,  0,  7],
       [29, 54, 62, 28, 89],
       [76, 92, 10,  4, 57]])

In [35]:
# 3 Print the grades average of each student

A.mean(axis = 1)

array([26.8, 52.4, 47.8])

In [36]:
# 4 Print the standard deviation of grades in each exam

A.std(axis = 0)

array([19.70335561, 36.46307112, 24.51303508, 12.36482466, 33.74413529])

In [37]:
# 5 Print the index of the exam with the lowest average grade

A.mean(axis = 1).argmin()

0

In [38]:
# 6 Print the index of the student who got the highest grade in any exam

A.max(axis = 1).argmax()

2

In [39]:
# 7. Print the index of the student who has the highest average grade

A.mean(axis = 1).argmax()

1

In [42]:
# 8. Print all the exams in which the grades average was larger than 60

exam_avg = A.mean(axis = 0)

np.where(exam_avg > 60)

np.nonzero(exam_avg > 60)

(array([0, 1, 2, 4]),)

----

# Done!