<div class="alert alert-block alert-success">
    <b><p style="font-size: XX-large"> <font color="green">Array Operations</font></p></b></div>

* NumPy provides many operators that perform operations on entire arrays **element-wise** (meaning that they would be applied to every element in the array)

In [1]:
import numpy as np

In [2]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

----

<div class="alert alert-block alert-danger">
    <b><p style="font-size: XX-large"> <font color="purple">Arithmetics</font></p></b></div>

* Perform arithmetics in one array element-wise
* Perform arithmetics between arrays of the same shape

In [3]:
a + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [4]:
a * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
a / a


# Warning on division by zero, but not an error!
# Just replaced with nan

/var/folders/89/_6hncvcx6nv5nm59nsxxvp340000gn/T/ipykernel_8488/152546423.py:1: RuntimeWarning: invalid value encountered in divide
  a / a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
1 / a

# Also warning, but not an error instead infinity


/var/folders/89/_6hncvcx6nv5nm59nsxxvp340000gn/T/ipykernel_8488/825121509.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

---

<div class="alert alert-block alert-info">
    <b><p style="font-size: XX-large"> <font color="royalblue">Logicals</font></p></b></div>

1. We can compare arrays with scalars and  other arrays
    * Comparisons are element-wise and produce an array of boolean values


2. Use **`isclose (a,b)`** to check if the elements are close ” enough to each other. Comparing arrays with `==` may give incorrect result.

3. Use **`&`**, **`|`**, **`~`** for `and`, `or`, `not` between Boolean arrays.


In [8]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [9]:
a < 2

array([ True, False, False, False, False])

In [10]:
(2 * a)

array([ 2,  4,  6,  8, 10])

In [11]:
(a **2)

array([ 1,  4,  9, 16, 25])

In [12]:
(2 * a) > (a **2)

array([ True, False, False, False, False])

----

In [13]:
# generate an array of 5 evenly spaced numbers between 0 and 3.14

x = np.linspace(0, np.pi, 5)
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [14]:
# Use the trig function's golden formula

np.sin(x)**2 == (1 - np.cos(x)**2)

array([ True,  True,  True,  True, False])

In [15]:
# how to fix?

np.isclose(np.sin(x)**2, (1 - np.cos(x)**2))

array([ True,  True,  True,  True,  True])

---

In [16]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [17]:
(a > 2) & (a < 4)  # () is required for operator precedence rules

array([False, False,  True, False, False])

In [18]:
~ ( a > 2)

array([ True,  True, False, False, False])

---

# Done! 